import Head from 'next/head';

import Header from '../../components/header/Header';
import Footer from '../../components/footer/Footer';
import MovieGrid from '../../components/movie-grid/MovieGrid';
import PageHeader from '../../components/page-header/PageHeader';
import { category as cate } from '../api/tmdbApi';
import { useRouter } from 'next/router';

export default function Category() {
  const {
    query: { category },
  } = useRouter();

  return (
    <div>
      <Head>
        <title>{category === cate.movie ? 'Movies' : 'TV Series'} page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <PageHeader>
          {category === cate.movie ? 'Movies' : 'TV Series'}
        </PageHeader>
        <div className="container">
          <div className="section mb-3">
            <MovieGrid category={category} />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
