/* eslint-disable react/no-unknown-property */
import Head from 'next/head';
import Header from '../components/header/Header';
import HeroSlide from '../components/hero-slide/HeroSlide';
import Link from 'next/link';

import { category, movieType, tvType } from './api/tmdbApi';
import { OutlineButton } from '../components/button/Button';
import MovieList from '../components/movie-list/MovieList';
import Footer from '../components/footer/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <HeroSlide />
        <div className="container">
          <div className="section mb-3">
            <div className="section__header mb-2">
              <h2>Trending Movies</h2>
              <Link href="/movie">
                <OutlineButton className="small">
                  <a>View more</a>
                </OutlineButton>
              </Link>
            </div>
            <MovieList category={category.movie} type={movieType.popular} />
          </div>

          <div className="section mb-3">
            <div className="section__header mb-2">
              <h2>Top Rated Movies</h2>
              <Link href="/movie">
                <OutlineButton className="small">View more</OutlineButton>
              </Link>
            </div>
            <MovieList category={category.movie} type={movieType.top_rated} />
          </div>

          <div className="section mb-3">
            <div className="section__header mb-2">
              <h2>Trending TV</h2>
              <Link href="/tv">
                <OutlineButton className="small">
                  <a>View more</a>
                </OutlineButton>
              </Link>
            </div>
            <MovieList category={category.tv} type={tvType.popular} />
          </div>

          <div className="section mb-3">
            <div className="section__header mb-2">
              <h2>Top Rated TV</h2>
              <Link href="/tv">
                <OutlineButton className="small">View more</OutlineButton>
              </Link>
            </div>
            <MovieList category={category.tv} type={tvType.top_rated} />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
