import Head from 'next/head';
import Detail from '../../../components/detail/Detail';
import Footer from '../../../components/footer/Footer';
import Header from '../../../components/header/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Detail />
      </main>
      <Footer />
    </div>
  );
}
