import Head from 'next/head';
import { useState } from 'react';
import Detail from '../../../components/detail/Detail';
import Footer from '../../../components/footer/Footer';
import Header from '../../../components/header/Header';

export default function Home() {
  const [title, setTitle] = useState();
  const renderTitle = (title) => {
    setTitle(title);
  };

  return (
    <div>
      <Head>
        <title>{title ? title : 'Detail Page'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Detail renderTitle={renderTitle} />
      </main>
      <Footer />
    </div>
  );
}
